
mock-recv:
	cargo run --bin mock-receiver

server:
	cargo run --bin server

client:
	cargo run --bin client

client-test:
	cargo run --bin client -- test

.PHONY: mock-recv server client client-test
